///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String iconsBackIcon = 'assets/icons/back-icon.svg';
  static const String iconsDate = 'assets/icons/date.svg';
  static const String iconsEdit = 'assets/icons/edit.svg';
  static const String iconsEmail = 'assets/icons/email.svg';
  static const String iconsFacebook = 'assets/icons/Facebook.svg';
  static const String iconsGoogle = 'assets/icons/Google.svg';
  static const String iconsLogo = 'assets/icons/Logo.svg';
  static const String iconsPassword = 'assets/icons/password.svg';
  static const String iconsUser = 'assets/icons/user.svg';
  static const String imagesCheckCorrect = 'assets/images/check_correct.png';
  static const String imagesOnboarding1 = 'assets/images/onboarding_1.png';
  static const String imagesOnboarding2 = 'assets/images/onboarding_2.png';
  static const String imagesOnboarding3 = 'assets/images/onboarding_3.png';
  static const String imagesSplash = 'assets/images/Splash.png';
}
